### ISSUE TITLE
New Example Code -- Controls Main from Buttons

### ISSUE THREAD

**Issue by PBenja3028** [pimoroni/button-shim#16]
I have uploaded some example code which illustrates passing a global variable from the button handlers in order to control the main program.  I am new to GitHub, so I'm not sure you will be able to get to my repository.  Had I had a simple example like this, it would have saved me a lot of time in development.  Hope this helps someone.

**Comment by Gadgetoid** [comment]
Is this the example you're talking about? https://github.com/PBenja3028/Pimoroni-Button-Shim/blob/master/buttonshim_control_main.py

You make a good case- would you like me to guide you through the process of "forking" this repository, adding your example, submitting a "pull request" here, stepping through code review and finally getting it merged? If you're new, it's a workflow worth learning!

**Comment by PBenja3028** [comment]
Yes, this is the example.  I’d welcome your help in learning the workflow.

**Comment by Gadgetoid** [comment]
You've already got a fork of the button shim repository, which is a good start.

You should check out your fork - https://github.com/PBenja3028/button-shim - add the example, and push it.

After making a change to your copy of this library/repository, if you view the page while logged in - https://github.com/PBenja3028/button-shim- then GitHub will ask if you want to raise a Pull Request to request that your new change be pulled into this repository.

In your example you've already got a pretty good handle on the code style, but you should make sure the filename uses dashes instead of underscores.
