### ISSUE TITLE
Please align Button shim LED API with Blinkt! API

### ISSUE THREAD

**Issue by TheDiveO** [pimoroni/button-shim#3]
As far as I see, the LED on the button shim is the same RGB LED pixel that is used on the Blinkt! pHAT. It would be easier to program with both shims/pHATs if the API would be more uniform, if possible.

The Blinkt! pHAT allows control of the PWM pixel brightness via `set_brightness(brightness)` with the `brightness` parameter ranging from 0.0 to 1.0. In contrast, the button shim has the PWN brightness hardcoded as "level" 31 (11111b).

Also, the Blinkt! pHAT has `set_pixel(x, r, g, b, brightness=None)` which allows the brightness to be controlled independently from the RGB channel values. This actually gives better control, especially in the low brightness region -- the RGB pixel LEDs are _very_ bright, so this better control is desirable.

**Comment by Gadgetoid** [comment]
Looks like I've painted myself into a corner here. There's a whole nightmare of colour scaling/brightness/gamma interplay that can happen, and getting it all to make sense is tricky.

We tend to just pick a sensible default and drop support for user modification of the APA102 global brightness for the sake of simplicity. Still, I understand why you might want it.

Currently brightness is treated as a scale factor on the RGB values, before they are then gamma corrected for display. So `255, 0, 0` with a brightness of 0.5 actually ends up being scaled to `127, 0, 0` and then corrected by the `LED_GAMMA` table to `54, 0, 0`.

The trouble, as you may have noticed, with `LED_GAMMA` is that when you try to go for really low-brightness lighting the first 22 steps of the gamma table are remapped to 0. So anything from 0-21 is 0. Making your low brightness red `15, 0, 0` basically off.

As you point out, re-introducing global brightness fixes this, sort of, by letting you simply dim the LEDs globally and display a brighter red at a lower intensity.

Unfortunately the global brightness of the APA-102 is applied *after* gamma correction. I don't know how big a deal this is, but it results in slightly different values:

 Let's say we start with the colour: `255, 128, 0`

Now we dim it to 50% in Python, by just multiplying by 0.5 and casting to an int: `127, 64, 0`

Now we gamma correct and get: `54, 11, 0`

What if we gamma correct first, and assume that 50% of the APA102s global brightness is the same as dividing the colour by two:

`255, 128, 0 => 255, 55, 0 => 127, 27, 0`

We've ended up with a slightly different colour at a very different brightness level.

My ideal solution would be something that takes care of the APA102 brightness value and colour scaling automagically- producing the best possible colour representation it can with any given colour and brightness. IE it would be clever enough to make: `10, 0, 0, 0.1` a visible colour at the lowest global brightness setting, rather than the off it currently is.

It's this conundrum that just makes me leave global brightness well alone on Button SHIM. I'm open to re-implementing it as another option specifically targeting global brightness, but there must be a better way.

Oh and to add fuel to the fire- Blinkt! is currently wrong. It has no gamma correction at all, and in my experience (although this is waaaay more obvious on things like Unicorn HAT and Unicorn HAT HD) this leads to horrible colour reproduction that's visibly wrong and (IIRC) washed out.

**Comment by TheDiveO** [comment]
Thank you very much for your detailed answer. So far, I was only sticking to the simple "base" colors, red, green, blue, yellow ... albeit with yellow I already noticed that 1,1,0 isn't very yellow-ish.

**Comment by Gadgetoid** [comment]
It's a wonderfully complicated issue that drives me completely bonkers. It needs a good day or so sitting down and figuring out how to intelligently adjust the brightness of individual pixels to better represent the various possible colours.

The built-in brightness of the APA102 LEDs isn't terribly great anyway, since it's a comparatively low-frequency PWM gate overlaid on top of the individual LED PWM outputs. But I do wonder if perhaps 64,64,0 at the lowest possible APA102 brightness setting is a better low-brightness reproduction of yellow than 1,1,0 at maximum APA102 brightness.

Needs some exhaustive testing!

The great APA102 guide/blog here: https://cpldcpu.com/2014/08/27/apa102/

Actually suggests that some people might see flicker when the global brightness is at 30 or below. You can see the overlaid PWM frequencies quite clearly in the scope captures. The brightness frequency is ~582 Hz while the colour frequency is 19.2 kHz. Now I'm not convinced anything in the 500 Hz ballpark produces visible flicker, but then I've never been particularly sensitive to LED flicker anyway (I think growing up with terrible monitors caused my brain to simply cancel it out).

**Comment by Gadgetoid** [comment]
To throw an additional spanner into the works of the wider APA102 landscape, we actually now have 2020 APA102s that have a dramatically different colour reproduction curve- IE: it's abundantly clear to just the casual observer.

I'm going to backburner this for now, since fully exploring the nuances of the APA102s brightness and how that affects colour reproduction is a task I'm not soon likely to have the time for.
